version: 2
project_name: rejson

builds:
  - builder: rust
    binary: rejson
    targets:
      - aarch64-apple-darwin
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - x86_64-unknown-linux-gnu
      - x86_64-unknown-linux-musl

archives:
  - files: ["nope*"] # Don't add LICENSE/README/etc.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if contains .Target "musl" }}-musl{{ end }}

release:
  draft: true
  header: |
    ## Release {{.ProjectName}} v{{.Version}}
  footer: |
    > linux_amd64-musl package contains a binary built against musl rather than libgcc. This is the package you should use if running on alpine.

dockers_v2:
  - images:
      - pseudomuto/{{.ProjectName}}

    platforms:
      - linux/amd64

    tags:
      - "{{.Version}}"
      - "{{.Major}}"
      - "{{.Major}}.{{.Minor}}"
      - latest

    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "A utility for managing a collection of secrets in source control"
      "org.opencontainers.image.url": "https://github.com/pseudomuto/{{ .ProjectName }}"
      "org.opencontainers.image.source": "https://github.com/pseudomuto/{{ .ProjectName }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"

    extra_files:
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
