max_width = 120
use_field_init_shorthand = true
use_try_shorthand = true

comment_width = 120
wrap_comments = true

group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
