name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@84c0677f58dcedf3b91f8223ce36a9ea5b3c84b7 # v15

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2

      - name: Toolchain info
        run: |
          nix develop --command cargo --version --verbose
          nix develop --command rustc --version
          nix develop --command clippy-driver --version
          nix develop --command rustfmt --version

      - name: Install coverage tool
        run: nix develop --command cargo install cargo-llvm-cov

      - name: Run CI pipeline
        run: nix develop --command task ci

      - name: Check MSRV
        run: nix develop --command task check:msrv

      - name: Generate coverage report
        run: nix develop --command cargo llvm-cov --lcov --output-path coverage.lcov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          files: ./coverage.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
